version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "release-note-none"
    - "kind/misc"
    ignore:
    - dependency-name: "k8s.io/*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "daily"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "release-note-none"
    - "kind/misc"
    ignore:
    - dependency-name: "k8s.io/*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "gomod"
    directory: "/test/custom-task-ctrls/wait-task-alpha"
    schedule:
      interval: "daily"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "release-note-none"
    - "kind/misc"
    ignore:
    - dependency-name: "k8s.io/*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "gomod"
    directory: "/test/custom-task-ctrls/wait-task-beta"
    schedule:
      interval: "daily"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "release-note-none"
    - "kind/misc"
    ignore:
    - dependency-name: "k8s.io/*"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
    - "ok-to-test"
    - "dependencies"
    - "release-note-none"
    - "kind/misc"

  - package-ecosystem: docker
    directory: /test/gohelloworld
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /vendor/github.com/tektoncd/plumbing
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /vendor/go.opentelemetry.io/otel
    schedule:
      interval: daily
